development:
  adapter: postgresql
  database: budget-development
  host: localhost
  encoding: unicode
  pool: 5
  timeout: 5000

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

