#!/usr/bin/env ruby -w
require 'digest/md5'

def if_changed(filename)
  last_digest_filename = ".#{filename.gsub('/', '_')}"
  last_digest = File.read(last_digest_filename) rescue ""
  current_digest = Digest::MD5.hexdigest(File.read(filename))

  unless last_digest.eql? current_digest
    yield
    File.write(last_digest_filename, current_digest)
  end
end

if_changed("Gemfile.lock") do
  system "bundle"
end

if_changed("db/schema.rb") do
  system "rake db:reset"
end

system "script/rails server"

